version: "3.9"
services:
  api:
    build: ./api
    ports: ["8000:8000"]
    env_file: .env
    depends_on: [redis, postgres]

  worker:
    build: ./worker
    env_file: .env
    depends_on: [redis, postgres]

  redis:
    image: redis:7

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
